### ISSUE TITLE
can not open random.lib while running install_lightspeed

### ISSUE THREAD

**Issue by KHBHH** [tminka/lightspeed#6]
Hi,

I am trying to run install_lightspeed, afer I have downloaded lightspeed files and added its path to my matlab directory. The matlab version that I have is (R2018b), but I am getting an error regarding random.lib, which is confusing, what do you advice me to do?

These are the steps I did while trying to solve for it:

First I ran to this error: 
**Error using mex**
**LINK:fatalerrorLNK1181:cannotopeninputfile'C:\ProgramFiles\MATLAB\R2018b\extern\lib\win64\MSVC150\libmwblas.lib'**

As a solution I renamed  **mingw64** to **MSVC150** in C:\Program Files\MATLAB\R2018b\extern\lib\win64

Then I tried running again install_lightspeed, and I got the following:
>> install_lightspeed
Compiling lightspeed 2.7 mex files...
Using the lapack library at C:\Program Files\MATLAB\R2018b\extern\lib\win64\MSVC150\libmwlapack.lib
mex -largeArrayDims  -silent  -DBLAS64 solve_triu.c "C:\Program Files\MATLAB\R2018b\extern\lib\win64\MSVC150\libmwlapack.lib" "C:\Program Files\MATLAB\R2018b\extern\lib\win64\MSVC150\libmwblas.lib"
install_random.bat "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\" x86
"Could not find either of these files:" 
"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\"\VC\vcvarsall.bat 
"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\"\Common7\Tools\vsvars32.bat 
"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\"\VC98\bin\vcvars32.bat 
**Error using mex
LINK : fatal error LNK1181: cannot open input file 'random.lib'**

After that, I copied vsvarshall into the path C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\"\VC\ and when I rand again install_lightspeed, the error was changed into: 

>> install_lightspeed
Compiling lightspeed 2.7  mex files...
Using the lapack library at C:\Program Files\MATLAB\R2018b\extern\lib\win64\MSVC150\libmwlapack.lib
mex -largeArrayDims  -silent  -DBLAS64 solve_triu.c "C:\Program Files\MATLAB\R2018b\extern\lib\win64\MSVC150\libmwlapack.lib" "C:\Program Files\MATLAB\R2018b\extern\lib\win64\MSVC150\libmwblas.lib"
install_random.bat "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\" x86
**The specified configuration type is missing.  The tools for the 
configuration might not be installed. 
'cl' is not recognized as an internal or external command, 
operable program or batch file. 
'link' is not recognized as an internal or external command, 
operable program or batch file. 
Error using mex
LINK : fatal error LNK1181: cannot open input file 'random.lib'

Error in install_lightspeed (line 139)
    eval(['mex' flags 'randomseed.c util.obj random.lib'])**

**Comment by tminka** [comment]
Please undo everything you've just changed in your computer, and get the latest version of lightspeed.  it should be fixed there.

**Comment by KHBHH** [comment]
Hi,

Thank you for getting back to me. I did what you said, it somehow conintued the installation but I got stuck here: 

>> install_lightspeed
Compiling lightspeed 2.7 mex files...
Using the lapack library at C:\Program Files\MATLAB\R2018b\extern\lib\win64\Microsoft\libmwlapack.lib
mex -largeArrayDims  -silent  -DBLAS64 solve_triu.c "C:\Program Files\MATLAB\R2018b\extern\lib\win64\Microsoft\libmwlapack.lib" "C:\Program Files\MATLAB\R2018b\extern\lib\win64\Microsoft\libmwblas.lib"
install_random.bat "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\" x86
********************************************************************** 
** Visual Studio 2017 Developer Command Prompt v15.8.4 
** Copyright (c) 2017 Microsoft Corporation 
********************************************************************** 
[vcvarsall.bat] Environment initialized for: 'x86' 
Microsoft (R) C/C++ Optimizing Compiler Version 19.15.26729 for x86 
Copyright (C) Microsoft Corporation.  All rights reserved. 
 
random.c 
Microsoft (R) Incremental Linker Version 14.15.26729.0 
Copyright (C) Microsoft Corporation.  All rights reserved. 
 
   Creating library random.lib and object random.exp 
**Error using mex
   Creating library randomseed.lib and object randomseed.exp
randomseed.obj : error LNK2019: unresolved external symbol ResetSeed referenced in function mexFunction
randomseed.obj : error LNK2019: unresolved external symbol SetSeed referenced in function mexFunction
randomseed.obj : error LNK2019: unresolved external symbol GetSeed referenced in function mexFunction
random.lib : warning LNK4272: library machine type 'x86' conflicts with target machine type 'x64'
randomseed.mexw64 : fatal error LNK1120: 3 unresolved externals**



Error in install_lightspeed (line 139)
    eval(['mex' flags 'randomseed.c util.obj random.lib'])

Appreciate your help!

**Comment by tminka** [comment]
I've made another change that should fix this problem.

**Comment by KHBHH** [comment]
Thank you for getting back to me again, the latter one fixed the problem!

Thanks!

**Comment by KHBHH** [comment]
I have used CSS trick to put all the plots in a panel, I used a seperate html file and included its path to R. 

After testing it on https://hmsimmunodept.shinyapps.io/DNARchitect_qa/ please provide me you toughts.

I have included the plots here and the download buttons in html documentation, but when I tested downloading the plots on Chrome, it was fine. In IE and Edge it was downloaded but the page went gray. Probably, the html documentation of the shiny download button that I used might not be supported in IE and Edge, so I will change it back to shiny button. You can test the link for now.

**Comment by tminka** [comment]
Your last comment doesn't seem relevant to lightspeed.

**Comment by pastorpflores** [comment]
Hi, I've downloaded the last version, but I'm still having this problem (on matlab 2018b & Microsoft Visual Studio 14.0):

Error using mex 
LINK : fatal error LNK1181: cannot open input file 'random.lib'

on:

Error in install_lightspeed (line 139)
    eval(['mex' flags 'randomseed.c util.obj random.lib'])

**Comment by tminka** [comment]
Can you post the full output of install_lightspeed?

**Comment by pastorpflores** [comment]
>> install_lightspeed
Compiling lightspeed 2.7 mex files...
Using the lapack library at C:\Program Files\MATLAB\R2018b\extern\lib\win64\Microsoft\libmwlapack.lib
mex -largeArrayDims  -silent  -DBLAS64 solve_triu.c "C:\Program Files\MATLAB\R2018b\extern\lib\win64\Microsoft\libmwlapack.lib" "C:\Program Files\MATLAB\R2018b\extern\lib\win64\Microsoft\libmwblas.lib"
install_random.bat "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\..\" x86_amd64
"Could not find either of these files:" 
"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\..\"\VC\Auxiliary\Build\vcvarsall.bat 
"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\..\"\VC\vcvarsall.bat 
"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\..\"\Common7\Tools\vsvars32.bat 
"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\..\"\VC98\bin\vcvars32.bat 
Error using mex
LINK : fatal error LNK1181: cannot open input file 'random.lib'



Error in install_lightspeed (line 139)
    eval(['mex' flags 'randomseed.c util.obj random.lib'])

**Comment by pastorpflores** [comment]
```
Compiling lightspeed 2.7 mex files...
Using the lapack library at C:\Program Files\MATLAB\R2018b\extern\lib\win64\Microsoft\libmwlapack.lib
mex -largeArrayDims  -silent  -DBLAS64 solve_triu.c "C:\Program Files\MATLAB\R2018b\extern\lib\win64\Microsoft\libmwlapack.lib" "C:\Program Files\MATLAB\R2018b\extern\lib\win64\Microsoft\libmwblas.lib"
install_random.bat "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\..\" x86_amd64
"Could not find either of these files:" 
"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\..\"\VC\Auxiliary\Build\vcvarsall.bat 
"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\..\"\VC\vcvarsall.bat 
"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\..\"\Common7\Tools\vsvars32.bat 
"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\..\"\VC98\bin\vcvars32.bat 
Error using mex
LINK : fatal error LNK1181: cannot open input file 'random.lib'



Error in install_lightspeed (line 139)
    eval(['mex' flags 'randomseed.c util.obj random.lib'])
```

**Comment by tminka** [comment]
Something's gone wrong with the compiler path.  Can you post the output of this command?
```
mex.getCompilerConfigurations('c','selected')
```

**Comment by pastorpflores** [comment]
mex.getCompilerConfigurations('c','selected')

ans = 

  CompilerConfiguration with properties:

             Name: 'Microsoft Visual C++ 2015 (C)'
     Manufacturer: 'Microsoft'
         Language: 'C'
          Version: '14.0'
         Location: 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\..\'
        ShortName: 'MSVC140'
         Priority: 'B5'
          Details: [1×1 mex.CompilerConfigurationDetails]
       LinkerName: 'link'
    LinkerVersion: ''
           MexOpt: 'C:\Users\Pastorpflores\AppData\Roaming\MathWorks\MATLAB\R2018b\mex_C_win64.xml'

**Comment by tminka** [comment]
It looks like vcvarsall.bat is missing.  See [this thread](https://social.msdn.microsoft.com/Forums/en-US/1071be0e-2a46-4c30-9546-ea9d7c4755fa/where-is-vcvarsallbat-file).

**Comment by pastorpflores** [comment]
> It looks like vcvarsall.bat is missing. See [this thread](https://social.msdn.microsoft.com/Forums/en-US/1071be0e-2a46-4c30-9546-ea9d7c4755fa/where-is-vcvarsallbat-file).

thanks, It solved my problem. 
Thank you!

**Comment by George614** [comment]
Hi tminka,

I have the same problem. I have installed Visual C++ 2017 and checked the previous posts but those did not solve the problem here.

CompilerConfiguration with properties:

             Name: 'Microsoft Visual C++ 2017 (C)'
     Manufacturer: 'Microsoft'
         Language: 'C'
          Version: '15.0'
         Location: 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\'
        ShortName: 'MSVC150'
         Priority: 'B7'
          Details: [1×1 mex.CompilerConfigurationDetails]
       LinkerName: 'link'
    LinkerVersion: ''
           MexOpt: 'C:\Users\zy8981.GOL3600-02\AppData\Roaming\MathWorks\MATLAB\R2017b\mex_C_win64.xml'`

Original error message:

`
Compiling lightspeed 2.7 mex files...
Using the lapack library at C:\Program Files\MATLAB\R2017b\extern\lib\win64\Microsoft\libmwlapack.lib
mex -largeArrayDims  -silent  -DBLAS64 solve_triu.c "C:\Program Files\MATLAB\R2017b\extern\lib\win64\Microsoft\libmwlapack.lib" "C:\Program Files\MATLAB\R2017b\extern\lib\win64\Microsoft\libmwblas.lib"
install_random.bat "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\" x86_amd64
********************************************************************** 
** Visual Studio 2017 Developer Command Prompt v15.5.5 
** Copyright (c) 2017 Microsoft Corporation 
********************************************************************** 
[vcvarsall.bat] Environment initialized for: 'x86_x64' 
Microsoft (R) C/C++ Optimizing Compiler Version 19.12.25835 for x64 
Copyright (C) Microsoft Corporation.  All rights reserved. 
 
random.c 
c1: fatal error C1083: Cannot open source file: 'random.c': No such file or directory 
Microsoft (R) Incremental Linker Version 14.12.25835.0 
Copyright (C) Microsoft Corporation.  All rights reserved. 
 
LINK : fatal error LNK1181: cannot open input file 'random.obj' 
Error using mex
LINK : fatal error LNK1181: cannot open input file 'random.lib'



Error in install_lightspeed (line 139)
    eval(['mex' flags 'randomseed.c util.obj random.lib'])
`

I have the vcvarsall.bat file in the "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC" folder.

Thanks!

**Comment by tminka** [comment]
It's not really the same problem.  In your case, the key line is:
```
c1: fatal error C1083: Cannot open source file: 'random.c': No such file or directory
```
Lightspeed can't compile a file that it can't open.
